name = "chatgpt-telegram-workers"
compatibility_date = "2023-03-04"
main = "./dist/index.js"
workers_dev = true
kv_namespaces = [
  { binding = "DATABASE", id = "<KV_ID>" }
]

[vars]

# OpenAI API Key
API_KEY = "OpenAI API Key"

# 机器人的token
TELEGRAM_TOKEN = "Telegram Bot Token"

# 当前workers同时绑定多个bot时候,在这里填写所有token,用逗号分隔
# TELEGRAM_AVAILABLE_TOKENS = "Available Telegram Bot Tokens"

# workers的域名
WORKERS_DOMAIN = "Workers Domain"

# 关闭白名单，允许所有人访问
I_AM_A_GENEROUS_PERSON = "false"

# 允许访问的用户列表,用逗号分隔
CHAT_WHITE_LIST = "Chat White List"

