name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: touch wrangler.toml
      - run: |
          cat << 'EOF' > wrangler.toml
          ${{secrets.WRANGLER_TOML}} 
          EOF
      - run: npm install
      - run: CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }} npm run wrangler publish --config=wrangler.toml

      - name: Check CF_WORKERS_DOMAIN exists
        run: |
          url=${{ secrets.CHATGPT_URL }}
          if [ -z "$url" ]; then
            echo "CHATGPT_URL does not exist"
          else
            echo "CHATGPT_URL exists"
            curl -s -o /dev/null https://$url/init
          fi
